version: "3.6"
services:
  wireguard:
    build: .
    image: ryansch/wireguard:latest
    privileged: true
    network_mode: host
    volumes:
      - /usr/src:/usr/src
      - /usr/lib/linux-kbuild-4.9:/usr/lib/linux-kbuild-4.9:ro
      - /lib/modules:/lib/modules

